#  Pipeline for building and publishing msteams-jira project
image: atlassian/default-image:4

options:
  docker: true
  size: 2x
definitions:
  services:
    docker:
      memory: 5000
  steps:
    - step: &dockerImage
        name: Prepare custom Docker image
        services:
          - docker
        caches:
          - docker
        script: 
          - pipe: atlassian/artifactory-sidekick:v1
          - source .artifactory/activate.sh
          - export IMG_TAG=docker.atl-paas.net/atlassian/netrunners/dotnet-node
          - docker build --tag="$IMG_TAG" --file docker/Dockerfile .
          - docker push "$IMG_TAG"
    - step: &build
        name: Build and Test
        image: 
          name: docker-proxy.services.atlassian.com/atlassian/netrunners/dotnet-node
          username: netrunners
          password: $PIPELINES_JWT_TOKEN
        caches:
          - dotnetcore
          - node
        script:
          - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
          - dotnet build -c Release
          - dotnet test --no-build -c Release --logger:"junit;LogFilePath=$REPORTS_PATH/test-result.xml"
    - step: &publish
        name: Publish application
        image:
          name: docker-proxy.services.atlassian.com/atlassian/netrunners/dotnet-node
          username: netrunners
          password: $PIPELINES_JWT_TOKEN
        script:
          - dotnet publish -c Release -o 'publish'
          - cd publish; zip -r ../jira-$BITBUCKET_BUILD_NUMBER.zip .; cd ..
        artifacts:
          - jira-*.zip
    - step: &deploy
        name: Deploy application
        deployment: Integration
        script:
          - pipe: atlassian/azure-web-apps-deploy:1.1.0
            variables:
              AZURE_APP_ID: $AZURE_APP_ID
              AZURE_PASSWORD: $AZURE_PASSWORD
              AZURE_TENANT_ID: $AZURE_TENANT_ID
              AZURE_RESOURCE_GROUP: $AZURE_RESOURCE_GROUP
              AZURE_APP_NAME: $AZURE_APP_NAME
              ZIP_FILE: 'jira-$BITBUCKET_BUILD_NUMBER.zip'
              SLOT: $AZURE_SLOT

pipelines:
  default:
    - step: 
        <<: *dockerImage
        condition:
          changesets:
            includePaths:
              - 'docker/**'
    - step: *build
  custom:
    buildDockerImage:
      - step: *dockerImage
  branches:
      master:
        - step: *build
        - step: *publish
        - step:
            <<: *deploy
            name: Deploy to integration
            deployment: Integration
        - step:
            <<: *deploy
            name: Deploy to staging
            deployment: Staging
            trigger: manual
