name: CI Gated

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          clean: false

      - name: Replace JiraMicrosoftTeamsIntegration version
        uses: rvolo/xml-replace-action@v0.3
        with:
          filepath: "${{ github.workspace}}/src/MicrosoftTeamsIntegration.Jira/MicrosoftTeamsIntegration.Jira.csproj"
          xpath: "/Project/PropertyGroup/Version/text()"
          replace: "${{ github.run_number}}"

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Run build powershell script
        run: ./build/build.ps1 --isGatedBuild=True --no-restore
        shell: powershell

      - name: Run tests
        run: dotnet test --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml"

      - name: Publish test report
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          junit_files: ${{ github.workspace }}/tests/artifacts/*test-result.xml
